[book]
title = "Voting Methods Explained"
authors = ["Albert Ramos"]
language = "en"
src = "src"

[build]
build-dir = "book"

[preprocessor.admonish]
command = "mdbook-admonish"

[output.html]
git-repository-url = "https://github.com/albertintech/voting-methods-explained.git"
additional-css = ["./mdbook-admonish.css"]
