[book]
title = "Voting Methods Explained"
authors = ["Albert Ramos"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/albertintech/voting-methods-explained.git"
sidebar-header-nav = true
